name: CosmicSpinners
version: '0.1.0-alpha01'
main: net.sierr.cosmicSpinners.CosmicSpinnersPlugin
api-version: '1.21'
authors: [ Starvern ]
softdepend: [UltimateUserInterface, PlaceholderAPI]
description: An advanced spinning particle cosmetics system
website: sierr.net
commands:
  spinner:
    permission: cosmicspinners.command
    description: Manage spinners
    aliases: [spinner, spin]
permissions:
  cosmicspinners.command:
    description: Usage of /spinner
    default: true
  cosmicspinners.command.reload:
    description: Usage of /spinner reload
    default: op
  cosmicspinners.hide:
    description: Hides all spinners
    default: false